import {
    LayoutDashboard,
    Activity,
    BadgeInfo,
    Search,
    FileText,
    Flame,
    Map,
    Phone,
    History,
    Database,
    MapPin,
    Layers3,
    MapPinned,
    Users,
    BarChart3,
    ClipboardList,
    Table,
} from "lucide-react";

import {
    Dashboard,
    Sinottico,
    AperturaChiusuraSOR,
    Ricerca,
    SegnalazioneGenerica,
    EventiAIB,
    MonitoraggioCOC,
    StoricoChiamate,
    StoricoVVFEstrazione,
    StoricoVVFMappatura,
    EmergencyScenarios,
    EmergencyManagement,
    TelefonataRep,
    TabellaRiassuntiva,
    EventiInAtto,
    MappaEventi,
    MappaInterventiVVF,
    MappaClusterVVF,
    MappaStatoCOC,
    MappaAttivitaOrganizzazioni,
    RicercaRecapiti,
    Reportistica,
} from "../../pages/segnalazioni";

const routes = [
    { label: "Dashboard", path: "dashboard", element: Dashboard, icon: LayoutDashboard, category: "Generale" },
    { label: "Sinottico", path: "sinottico", element: Sinottico, icon: Activity, category: "Generale" },
    { label: "Apertura/chiusura SOR", path: "apertura-chiusura-sor", element: AperturaChiusuraSOR, icon: BadgeInfo, category: "Generale" },
    { label: "Ricerca", path: "ricerca", element: Ricerca, icon: Search, category: "Generale" },
    { label: "Segnalazione generica", path: "segnalazione-generica", element: SegnalazioneGenerica, icon: FileText, category: "Generale" },
    { label: "Eventi AIB", path: "eventi-aib", element: EventiAIB, icon: Flame, category: "Generale" },
    { label: "Monitoraggio COC", path: "monitoraggio-coc", element: MonitoraggioCOC, icon: Map, category: "Generale" },
    { label: "Storico Chiamate", path: "storico-chiamate", element: StoricoChiamate, icon: Phone, category: "Storico" },
    { label: "Storico VVF Estrazione", path: "storico-vvf-estrazione", element: StoricoVVFEstrazione, icon: History, category: "Storico" },
    { label: "Storico VVF Mappatura interventi", path: "storico-vvf-mappatura", element: StoricoVVFMappatura, icon: Database, category: "Storico" },
    { label: "Emergency scenarios", path: "emergency-scenarios", element: EmergencyScenarios, icon: Layers3, category: "Emergenze" },
    { label: "Emergency Management", path: "emergency-management", element: EmergencyManagement, icon: ClipboardList, category: "Emergenze" },
    { label: "Telefonata reperibilità", path: "telefonata-rep", element: TelefonataRep, icon: Phone, category: "Generale" },
    { label: "Tabella riassuntiva", path: "tabella-riassuntiva", element: TabellaRiassuntiva, icon: Table, category: "Generale" },
    { label: "Eventi in atto", path: "eventi-in-atto", element: EventiInAtto, icon: Activity, category: "Generale" },

    // CATEGORIA MAPPE
    { label: "Mappa eventi", path: "mappa-eventi", element: MappaEventi, icon: MapPin, category: "Mappe" },
    { label: "Mappa Interventi VVF", path: "mappa-interventi-vvf", element: MappaInterventiVVF, icon: MapPinned, category: "Mappe" },
    { label: "Mappa cluster eventi VVF", path: "mappa-cluster-vvf", element: MappaClusterVVF, icon: Layers3, category: "Mappe" },
    { label: "Mappa stato COC", path: "mappa-stato-coc", element: MappaStatoCOC, icon: Map, category: "Mappe" },
    { label: "Mappa att.tà organizzazioni", path: "mappa-attivita-organizzazioni", element: MappaAttivitaOrganizzazioni, icon: Users, category: "Mappe" },

    { label: "Ricerca recapiti", path: "ricerca-recapiti", element: RicercaRecapiti, icon: Search, category: "Generale" },
    { label: "Reportistica", path: "reportistica", element: Reportistica, icon: BarChart3, category: "Generale" },
];


export default routes;
