import {
    Dashboard,
    Sinottico,
    AperturaChiusuraSOR,
    Ricerca,
    SegnalazioneGenerica,
    EventiAIB,
    MonitoraggioCOC,
    StoricoChiamate,
    StoricoVVFEstrazione,
    StoricoVVFMappatura,
    EmergencyScenarios,
    EmergencyManagement,
    TelefonataRep,
    TabellaRiassuntiva,
    EventiInAtto,
    MappaEventi,
    MappaInterventiVVF,
    MappaClusterVVF,
    MappaStatoCOC,
    MappaAttivitaOrganizzazioni,
    RicercaRecapiti,
    Reportistica,
    GestioneSegnalazioni,
} from "../../pages/segnalazioni";

const routes = [
    { label: "Dashboard", path: "dashboard", element: Dashboard },
    { label: "Sinottico", path: "sinottico", element: Sinottico },
    { label: "Apertura/chiusura SOR", path: "apertura-chiusura-sor", element: AperturaChiusuraSOR },
    { label: "Ricerca", path: "ricerca", element: Ricerca },
    { label: "Segnalazione generica", path: "segnalazione-generica", element: SegnalazioneGenerica },
    { label: "Eventi AIB", path: "eventi-aib", element: EventiAIB },
    { label: "Monitoraggio COC", path: "monitoraggio-coc", element: MonitoraggioCOC },
    { label: "Storico Chiamate", path: "storico-chiamate", element: StoricoChiamate },
    { label: "Storico VVF Estrazione", path: "storico-vvf-estrazione", element: StoricoVVFEstrazione },
    { label: "Storico VVF Mappatura interventi", path: "storico-vvf-mappatura", element: StoricoVVFMappatura },
    { label: "Emergency scenarios", path: "emergency-scenarios", element: EmergencyScenarios },
    { label: "Emergency Management", path: "emergency-management", element: EmergencyManagement },
    { label: "Telefonata rep", path: "telefonata-rep", element: TelefonataRep },
    { label: "Tabella riassuntiva", path: "tabella-riassuntiva", element: TabellaRiassuntiva },
    { label: "Eventi in atto", path: "eventi-in-atto", element: EventiInAtto },
    { label: "Mappa eventi", path: "mappa-eventi", element: MappaEventi },
    { label: "Mappa Interventi VVF", path: "mappa-interventi-vvf", element: MappaInterventiVVF },
    { label: "Mappa cluster eventi VVF", path: "mappa-cluster-vvf", element: MappaClusterVVF },
    { label: "Mappa stato COC", path: "mappa-stato-coc", element: MappaStatoCOC },
    { label: "Mappa att.tà organizzazioni", path: "mappa-attivita-organizzazioni", element: MappaAttivitaOrganizzazioni },
    { label: "Ricerca recapiti", path: "ricerca-recapiti", element: RicercaRecapiti },
    { label: "Reportistica", path: "reportistica", element: Reportistica },
    { label: "Gestione segnalazioni o telefonate", path: "gestione-segnalazioni", element: GestioneSegnalazioni },
];

export default routes;
